### ISSUE TITLE
Redeploy - Remove Squadlead from deployment, come back to Deploy specific vehicle? Like Comms Offroad or Water Offroad?

### ISSUE THREAD

**Issue by OverlordZorn** [ReconChickenARMA/HAM-Sefrou_Ramal#105]

**Comment by OverlordZorn** [comment]
@ReconChickenARMA
To which vehicles can the players currently deploy?

**Comment by ReconChickenARMA** [comment]
Theoretically, the players can depoly to the Unarmed Marid, the Comms Offroad, and the Typhoon Transport
