### ISSUE TITLE
Zeus Remotecontrol Change Language did not work?

### ISSUE THREAD

**Issue by OverlordZorn** [ReconChickenARMA/HAM-Sefrou_Ramal#134]

**Comment by ReconChickenARMA** [comment]
I think I have experienced something similar, I need to exit and reenter Zeus to return to the "default" language.

**Comment by OverlordZorn** [comment]
didnt work on dedicated during last patrol session -need to look into it again 😭

**Comment by OverlordZorn** [comment]
fixed by #155
