### ISSUE TITLE
Issue - Missionfilesize: 25+MB -> Image File Sizes

### ISSUE THREAD

**Issue by OverlordZorn** [ReconChickenARMA/HAM-Sefrou_Ramal#26]
![grafik](https://github.com/user-attachments/assets/a5bf0efe-d775-44ef-b4a4-34ec63cabe09)

**Comment by ReconChickenARMA** [comment]
File has been reduced to 13MB. Could go down more, but this is a pretty good improvement.
![Capture](https://github.com/user-attachments/assets/84e76bf5-a9b3-410c-b891-dc6b9e80d375)

**Comment by OverlordZorn** [comment]
YUGE improvement
