### ISSUE TITLE
ZEUS - No Zeus attached to the slot?

### ISSUE THREAD

**Issue by OverlordZorn** [ReconChickenARMA/HAM-Sefrou_Ramal#29]

**Comment by ReconChickenARMA** [comment]
The zeus modules were synced but I didn't define the owners. Resolved by assigning Coy CO and Coy QM slots with variable names, and making them owners of the modules.

**Comment by OverlordZorn** [comment]
That is the way to go, yea. i dont trust the syncing of modules and whatelse in the editor.
