### ISSUE TITLE
Arsenal - Add Basic Default Template so people can get their kit, change role stuff and are ready to go

### ISSUE THREAD

**Issue by OverlordZorn** [ReconChickenARMA/HAM-Sefrou_Ramal#40]

**Comment by OverlordZorn** [comment]
https://github.com/acemod/ACE3/blob/master/addons/arsenal/functions/fnc_addDefaultLoadout.sqf
`["Squad Leader", getUnitLoadout sql1] call ace_arsenal_fnc_addDefaultLoadout`

**Comment by OverlordZorn** [comment]
https://github.com/BrettMayson/CBA_A3/blob/db40acd55a19cd51908ada20c4bc53a6ba86e68e/addons/loadout/fnc_getLoadout.sqf
`[player] call CBA_fnc_getLoadout;`

**Comment by FirehawkFrostbite** [comment]
`[[[],[],["hgun_P07_F","","acc_flashlight_pistol","",["16Rnd_9x21_Mag_v2",17],[],""],["U_lxWS_UN_Camo3",[["ACE_EarPlugs",1],["ACE_SpraypaintGreen",1],["ACE_packingBandage",11],["ACE_bodyBag",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_salineIV_500",1],["ACE_splint",2],["ACE_tourniquet",2],["ACE_MapTools",1],["ACE_CableTie",3]]],["PLP_UNA_V_CarrierRigKBT_01_light_F",[["ACE_personalAidKit",1],["ACE_EntrenchingTool",1],["ACRE_PRC343",1],["16Rnd_9x21_Mag_v2",1,17],["SmokeShell",2,1],["MiniGrenade",2,1]]],["B_AssaultPack_cbr",[["ACE_WaterBottle",2],["ACE_MRE_BeefStew",1],["greenmag_item_speedloader",1],["greenmag_ammo_9x21_basic_30Rnd",1],["G_RegulatorMask_F",1],["ACE_Humanitarian_Ration",2]]],"PLP_UNA_H_Cap","",["Nikon_DSLR_HUD","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ChemicalDetector_01_watch_F",""]],[["grad_slingHelmet","lxWS_H_PASGT_basic_UN_F"],["ace_earplugs",true]]]`


Should have all basic needs covered now. UNA Helmet slung,

**Comment by OverlordZorn** [comment]
> `[[[],[],["hgun_P07_F","","acc_flashlight_pistol","",["16Rnd_9x21_Mag_v2",17],[],""],["U_lxWS_UN_Camo3",[["ACE_EarPlugs",1],["ACE_SpraypaintGreen",1],["ACE_packingBandage",11],["ACE_bodyBag",1],["ACE_epinephrine",2],["ACE_morphine",2],["ACE_salineIV_500",1],["ACE_splint",2],["ACE_tourniquet",2],["ACE_MapTools",1],["ACE_CableTie",3]]],["PLP_UNA_V_CarrierRigKBT_01_light_F",[["ACE_personalAidKit",1],["ACE_EntrenchingTool",1],["ACRE_PRC343",1],["16Rnd_9x21_Mag_v2",1,17],["SmokeShell",2,1],["MiniGrenade",2,1]]],["B_AssaultPack_cbr",[["ACE_WaterBottle",2],["ACE_MRE_BeefStew",1],["greenmag_item_speedloader",1],["greenmag_ammo_9x21_basic_30Rnd",1],["G_RegulatorMask_F",1],["ACE_Humanitarian_Ration",2]]],"PLP_UNA_H_Cap","",["Nikon_DSLR_HUD","","","",[],[],""],["ItemMap","ItemAndroid","","ItemCompass","ChemicalDetector_01_watch_F",""]],[["grad_slingHelmet","lxWS_H_PASGT_basic_UN_F"],["ace_earplugs",true]]]`
> 
> Should have all basic needs covered now. UNA Helmet slung,

you put your earplugs in in the arsenal on purpose?

**Comment by OverlordZorn** [comment]
assign to @OverlordZorn  (idk if that works lol)

**Comment by FirehawkFrostbite** [comment]
> you put your earplugs in in the arsenal on purpose?

yeah. I have them in always anyways, this way I can't forget and have a spare in case someone else forgets theirs. there's still enough space in uniform to take them out if you need to listen for something.
