### ISSUE TITLE
Arsenal - Add Pistol that can carry a Pistol Light

### ISSUE THREAD

**Issue by OverlordZorn** [ReconChickenARMA/HAM-Sefrou_Ramal#45]

**Comment by ReconChickenARMA** [comment]
I am happy to add the RF glock, I will probably add another non-dlc sidearm as well, not sure which one yet, but I will shop around

**Comment by ReconChickenARMA** [comment]
On further inspection, the P99 fits our needs well. It has mag compatibility with the other two, and it can mount a flashlight.
