### ISSUE TITLE
Base - Twitching Shipping container

### ISSUE THREAD

**Issue by OverlordZorn** [ReconChickenARMA/HAM-Sefrou_Ramal#60]
https://cdn-cf-east.streamable.com/video/mp4/ey7a67.mp4?Expires=1723736340&Signature=R9OzMHOq0ALZ2knU-RC3PTwyi-0fXhJZG49VcCAaEAMR95be45yYR5~Sq2ktIeXTh~BXVBVaj~TYXmLtvIvtypCkFMNMBc5NV3D2MspOLkH5ZbaWWHnc~f95y7jAmA-hZHBpYAIZ2rJyxASD~Ay5czwR1qfE2Zv2u6rHO82KUPBFKghcEv0GTyhjnNjmUzCXMkIfEOTKisDKWfMZSW3xoXq-Nmen1UkHis146W87ntL6VjdxyoxcWjbh3jdqNEkfgCSB1XPs4VRugH~TH63-5rJdYhK3vSZ8VQp4~RJ55Q3F5zlKUs7q0yScvnOutOiZdI~90Pll8wTXAL3r1Wh6dA__&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ

**Comment by OverlordZorn** [comment]
maybe make the inside fencegate a simple object?
Or disable collision between those two?

**Comment by OverlordZorn** [comment]
I tried to fix it with multiple different approaches, non of them successful.

At times, the twitching can get pretty extreme. At this point, we might wanna find a different solution.
Different solution meaning rearranging the situation.

Remove the Arsenal Laptop and maybe put it somewhere else.

keep it as a easer-egg, but maybe move the container to somewhere else, or just turn it around

and

leave it open, disable simulation to avoid twitching.

**Comment by ReconChickenARMA** [comment]
Sounds good to me, will do.
