### ISSUE TITLE
Arsenal - Drone Op

### ISSUE THREAD

**Issue by FirehawkFrostbite** [ReconChickenARMA/HAM-Sefrou_Ramal#64]
Thoughts on Gunbag for Drone-Operator?
Reason: Drone Op rifles don't fit in any backpack (not even the giant patrol pack). swapping between rifle and GL involves dropping rifle on the ground. 

`ace_gunbag_Tan`

**Comment by ReconChickenARMA** [comment]
Ah, good idea. I will add it to the arsenal.
