### ISSUE TITLE
Zeus action to add or remove reputation

### ISSUE THREAD

**Issue by ReconChickenARMA** [ReconChickenARMA/HAM-Sefrou_Ramal#65]
Is it possible to make a Zeus self-interact to raise or lower rep by a set amount? I want a way to reward the players outside of the normal game play mechanics for storytelling beats, or punish them, as the case may be.

**Comment by OverlordZorn** [comment]
doable... what number brackets you want?
+,- 25,50,100,150,250 ?

**Comment by ReconChickenARMA** [comment]
I think a +-5, 10, 20 is probably best, I think the mode starts at 200 rep, so I don't want to be throwing around huge rewards that bug out the mission.
=

**Comment by ReconChickenARMA** [comment]
Is it possible to also have an interaction to display the current rep?

**Comment by OverlordZorn** [comment]
btc_rep_global is a server only variable so its a bit more convoluted to actually get it retrieved - i have an idea but its eh.

**Comment by ReconChickenARMA** [comment]
Alrighty, if it's too much of a hassle, don't bother.
